### ISSUE TITLE
NPE in DeviceAddressSpeechlet

### ISSUE THREAD

**Issue by rmueller83** [alexa/legacy-skill-samples-java#1]
https://github.com/alexa/skill-samples-java/blob/1520b024a9eb0fd1a0c08506ac002309491a4ae9/address/src/com/amazon/asksdk/address/DeviceAddressSpeechlet.java#L129 fails with an NPE if the user has not given permission.

https://developer.amazon.com/docs/custom-skills/request-and-response-json-reference.html says "The `accessToken` field will not appear if null, and **the `permissions` object also will not appear if `consentToken` is null.**".

So the null check 2 lines below which checks the `consentToken` should be done on the `permission` object.

**Comment by TianTXie** [comment]
Fixed in commit e01634712652e238ea7535fc85ff051eed819eac
