### ISSUE TITLE
Can not instantiate value of type [simple type, class com.amazon.speech.json.SpeechletRequestEnvelope] from String value

### ISSUE THREAD

**Issue by kevin32** [alexa/legacy-skill-samples-java#11]
Hi, guys, I followed very briefly steps on readme.md.
When I tried to run a test on the console. This is the output I see.
Also added a [picture](https://ibb.co/jVepwH)

**Comment by ghost** [comment]
Hey there, do you mind showing us what your code looks like?

**Comment by kevin32** [comment]
Hi

Thanks for the reply, but I somehow managed to get it working.
