### ISSUE TITLE
Unable to upload jar in lambda function

### ISSUE THREAD

**Issue by Aravindhan95** [alexa/legacy-skill-samples-java#25]
Unable to upload jar file in lambda function it says "The deployment package of your Lambda function "helloAlexa" is too large to enable inline code editing. However, you can still invoke your function."

**Comment by Chris-Liao** [comment]
Hi @Aravindhan95 , can you tell us how big is your skill jar? Lambda function has limit on deployment package size 50 MB, as documented [here](https://docs.aws.amazon.com/lambda/latest/dg/limits.html).

**Comment by LorenzNickel** [comment]
Hey @Aravindhan95 , if you uploaded your compiled jar and get this output there's no problem, everything should be fine. As the error tells you, you just can't edit the code of your skill/function online in AWS and have to upload a new jar-file if you want to make any changes.

I get this warning for all my java-written skills deployed to AWS and they are working fine.
